Refactor ledger startup code
anoma/anoma pull request #1231
Opened 2022-07-11 12:50 UTC by sug0

I have broken down the `run_aux` function into several different logical units, which should make the ledger startup code more modular and easier to reason about.

This PR will help with the changes done to the eth bridge, since the latter will require even more startup logic code to manage `geth`. For the same reason, it is in conflict with #1196, so this will need to be handled.

2022-07-11 13:41 UTC, sug0 commented
CI timed out :\
```
+ sccache --start-server
sccache: Starting the server...
sccache: error: Timed out waiting for server startup
```

2022-07-11 14:53 UTC, batconjurer requested changes
Looks great to me. Just a couple of tiny things

2022-07-11 14:53 UTC, batconjurer commented on apps/src/lib/node/ledger/mod.rs
> +fn start_abci_broadcaster_shell(
Can I get some docstrings here?

2022-07-12 08:06 UTC, sug0 commented on apps/src/lib/node/ledger/mod.rs
> +fn start_abci_broadcaster_shell(
done

2022-07-12 13:55 UTC, tzemanovic commented
I tried to check the windows compilation, but unfortunately, we have a unix only dependency in the wallet `file-lock`, so it's not working atm. We don't officially support windows yet, so it's fine to go ahead - visually it seems fine to me :)

2022-07-12 13:56 UTC, tzemanovic commented
if you could just pls add a changelog (https://github.com/anoma/anoma/blob/master/CONTRIBUTING.md#opening-a-pull-request)

2022-07-13 11:49 UTC, sug0 commented
done! added a changelog entry

2022-08-03 14:27 UTC, juped commented
Moved to anoma/namada#270 anoma/namada#271

2022-08-03 14:27 UTC, closed without merging